from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

from yolo_developer.github.git import GitManager
from yolo_developer.github.issues import IssueManager
from yolo_developer.github.models import CommitResult, GitHubError
from yolo_developer.github.pr import PRManager
from yolo_developer.github.releases import ReleaseManager


@dataclass(frozen=True)
class StoryInfo:
    story_id: str
    title: str
    description: str
    acceptance_criteria: list[str]
    github_issue: int | None = None


class GitHubWorkflow:
    """Integrate GitHub operations into workflow steps."""

    def __init__(
        self,
        git: GitManager,
        prs: PRManager,
        issues: IssueManager,
        releases: ReleaseManager,
    ) -> None:
        self.git = git
        self.prs = prs
        self.issues = issues
        self.releases = releases

    def start_story(self, story: StoryInfo, branch_prefix: str) -> dict[str, object]:
        branch_name = self._generate_branch_name(story, branch_prefix)
        branch = self.git.create_branch(branch_name)
        issue = self.issues.create(
            title=f"[{story.story_id}] {story.title}",
            body=self._format_issue_body(story),
        )
        return {"branch": branch, "issue": issue}

    def complete_story(
        self,
        story: StoryInfo,
        files_changed: list[str],
        commit_message: str,
        pr_body: str,
        base_branch: str,
        labels: list[str] | None = None,
    ) -> dict[str, object]:
        if not files_changed:
            raise GitHubError(
                "No tracked changes to commit. Stage files or pass --file to select changes."
            )
        missing_files = [path for path in files_changed if not Path(path).exists()]
        if missing_files:
            missing_list = ", ".join(missing_files)
            raise GitHubError(f"Unable to stage missing files: {missing_list}")
        self.git.stage_files(files_changed)
        commit = self.git.commit(message=commit_message)
        self.git.push(set_upstream=True)
        pr = self.prs.create(
            title=f"[{story.story_id}] {story.title}",
            body=pr_body,
            head=self.git.get_current_branch().name,
            base=base_branch,
            issue_refs=[story.github_issue] if story.github_issue else None,
            labels=labels,
        )
        return {"commit": commit, "pr": pr}

    def _generate_branch_name(self, story: StoryInfo, prefix: str) -> str:
        slug = re.sub(r"[^a-z0-9]+", "-", story.title.lower()).strip("-")
        return f"{prefix}{story.story_id}-{slug[:40]}"

    def _format_issue_body(self, story: StoryInfo) -> str:
        criteria = "\n".join(f"- [ ] {item}" for item in story.acceptance_criteria)
        return f"""## User Story

{story.description}

## Acceptance Criteria

{criteria}

---
*Created by YOLO Developer*"""


def format_pr_body(story: StoryInfo, commit: CommitResult) -> str:
    criteria = "\n".join(f"- [ ] {item}" for item in story.acceptance_criteria)
    return f"""## Summary

{story.description}

## Changes

- {len(commit.files_changed)} files changed
- +{commit.insertions} / -{commit.deletions}

## Acceptance Criteria

{criteria}

## Testing

- [ ] Unit tests pass
- [ ] Integration tests pass
- [ ] Manual testing completed

---
*Generated by YOLO Developer*"""
