"""Configuration export and import for YOLO Developer.

This module provides functions to export configuration to portable YAML files
and import configurations from YAML files. API keys are excluded from exports
for security (NFR-SEC-1).

Export Usage:
    >>> from yolo_developer.config import load_config
    >>> from yolo_developer.config.export import export_config
    >>> config = load_config()
    >>> export_config(config, Path("exported.yaml"))

Import Usage:
    >>> from yolo_developer.config.export import import_config
    >>> import_config(Path("exported.yaml"), Path("yolo.yaml"))

Security Note:
    API keys (openai_api_key, openai.api_key, anthropic_api_key) are NEVER included
    in exports. They must be set via environment variables:
    - YOLO_LLM__OPENAI__API_KEY
    - YOLO_LLM__OPENAI_API_KEY (legacy)
    - YOLO_LLM__ANTHROPIC_API_KEY
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Any

import yaml

if TYPE_CHECKING:
    from yolo_developer.config.schema import YoloConfig

# Fields that contain secrets and should be excluded from export
SECRET_FIELDS = {"openai_api_key", "anthropic_api_key", "openai.api_key"}

# Header comment for exported files
EXPORT_HEADER = """# YOLO Developer Configuration
# Generated by export_config()
#
# API keys must be set via environment variables:
#   YOLO_LLM__OPENAI__API_KEY=your-openai-key-here
#   YOLO_LLM__OPENAI_API_KEY=your-openai-key-here  # legacy
#   YOLO_LLM__ANTHROPIC_API_KEY=your-anthropic-key-here

"""


def export_config(config: YoloConfig, output_path: Path) -> None:
    """Export configuration to YAML file, excluding secrets.

    Exports the configuration to a portable YAML file that can be shared
    or imported to other projects. API keys are excluded from the export
    for security reasons.

    Creates parent directories if they don't exist. Overwrites existing
    files without warning (standard behavior for config export tools).

    Args:
        config: The YoloConfig instance to export.
        output_path: Path where YAML file will be written.

    Example:
        >>> from yolo_developer.config import load_config
        >>> from yolo_developer.config.export import export_config
        >>> config = load_config()
        >>> export_config(config, Path("my-config.yaml"))
    """
    # Convert to dict, excluding secrets
    data = _config_to_exportable_dict(config)

    # Ensure parent directory exists
    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)

    # Write with header comment
    with open(output, "w", encoding="utf-8") as f:
        f.write(EXPORT_HEADER)
        yaml.safe_dump(data, f, default_flow_style=False, sort_keys=False)


def import_config(
    source_path: Path,
    target_path: Path | None = None,
) -> None:
    """Import configuration from YAML file.

    Imports a configuration file, validates it, and writes it to the target
    location. The configuration is validated before writing to ensure it's
    valid. Adds header comment explaining API key setup.

    Creates parent directories if they don't exist. Overwrites existing
    files without warning (standard behavior for config import tools).

    Args:
        source_path: Path to source YAML configuration.
        target_path: Path to write imported config. Defaults to ./yolo.yaml.

    Raises:
        ConfigurationError: If source file doesn't exist or is invalid.

    Example:
        >>> from yolo_developer.config.export import import_config
        >>> import_config(Path("exported.yaml"), Path("yolo.yaml"))
    """
    from yolo_developer.config.loader import ConfigurationError, _load_yaml_file
    from yolo_developer.config.schema import YoloConfig

    source = Path(source_path)
    if not source.exists():
        raise ConfigurationError(f"Configuration file not found: {source.absolute()}")

    # Load source YAML
    yaml_data = _load_yaml_file(source)

    # Validate by attempting to create config
    # This catches validation errors before writing
    try:
        YoloConfig(**yaml_data)
    except Exception as e:
        raise ConfigurationError(f"Invalid configuration in {source}: {e}") from e

    # Write to target with header comment
    target = Path(target_path) if target_path else Path("yolo.yaml")
    target.parent.mkdir(parents=True, exist_ok=True)

    with open(target, "w", encoding="utf-8") as f:
        f.write(EXPORT_HEADER)
        yaml.safe_dump(yaml_data, f, default_flow_style=False, sort_keys=False)


def _config_to_exportable_dict(config: YoloConfig) -> dict[str, Any]:
    """Convert config to dict, excluding secret fields.

    Args:
        config: The YoloConfig instance to convert.

    Returns:
        Dictionary representation with secrets removed.
    """
    data = config.model_dump(mode="json")

    # Remove secrets from llm section
    if "llm" in data:
        for field in SECRET_FIELDS:
            if "." in field:
                parent, child = field.split(".", 1)
                if parent in data["llm"] and isinstance(data["llm"][parent], dict):
                    data["llm"][parent].pop(child, None)
            else:
                data["llm"].pop(field, None)

    return data
