source "https://rubygems.org"

# Align with GitHub Pages' supported Jekyll stack.
gem "github-pages", "~> 232", group: :jekyll_plugins
gem "jekyll-remote-theme", group: :jekyll_plugins
gem "webrick", "~> 1.8"  # Required for Ruby 3.0+
