source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "just-the-docs", "~> 0.8"
gem "jekyll-seo-tag", "~> 2.8"
gem "jekyll-relative-links", "~> 0.7"
gem "webrick", "~> 1.8"  # Required for Ruby 3.0+
